using CashPulse.Core.Forecast;
using CashPulse.Core.Models;

namespace CashPulse.Core.Services;

/// <summary>
/// Генерирует проецируемые операции начисления процентов для вкладов
/// и сберегательных инвестиционных счетов.
/// Авто-операции не сохраняются в БД — генерируются в памяти при каждом расчёте прогноза.
/// </summary>
public class DepositAccrualService
{
    /// <summary>
    /// Генерирует список операций начисления процентов для счёта в горизонте [from, to].
    /// Вызывается из ForecastEngine после ExpandAllOperations.
    /// </summary>
    public List<ProjectedOperation> GenerateAccruals(
        Account account,
        decimal initialBalance,
        string currency,
        DateOnly from,
        DateOnly to)
    {
        if (account.InterestRate is null or <= 0) return [];
        if (initialBalance <= 0) return [];

        if (account.DailyAccrual == true)
            return GenerateDailyAccruals(account, initialBalance, currency, from, to);

        if (account.InterestAccrualDay is null) return [];

        var accrualDay = account.InterestAccrualDay.Value;
        var effectiveTo = account.DepositEndDate.HasValue
            ? DateOnly.FromDayNumber(Math.Min(to.DayNumber, account.DepositEndDate.Value.DayNumber))
            : to;

        var results = new List<ProjectedOperation>();

        var year = from.Year;
        var month = from.Month;

        while (new DateOnly(year, month, 1) <= new DateOnly(effectiveTo.Year, effectiveTo.Month, 1))
        {
            // Step 1: determine accrual date with fallback to last day of month
            var daysInMonth = DateTime.DaysInMonth(year, month);
            var actualDay = Math.Min(accrualDay, daysInMonth);
            var accrualDate = new DateOnly(year, month, actualDay);

            if (accrualDate < from)
            {
                AdvanceMonth(ref year, ref month);
                continue;
            }

            if (accrualDate > effectiveTo)
                break;

            // Step 2: determine previous accrual date to find the period
            var (prevYear, prevMonth) = month == 1
                ? (year - 1, 12)
                : (year, month - 1);

            var prevDaysInMonth = DateTime.DaysInMonth(prevYear, prevMonth);
            var prevAccrualDate = new DateOnly(prevYear, prevMonth, Math.Min(accrualDay, prevDaysInMonth));

            var periodStart = prevAccrualDate < from ? from : prevAccrualDate;
            var days = accrualDate.DayNumber - periodStart.DayNumber;

            if (days <= 0)
            {
                AdvanceMonth(ref year, ref month);
                continue;
            }

            // Step 3: calculate accrual amount
            var dailyRate = account.InterestRate.Value / 100m / 365m;
            var accrual = Math.Round(initialBalance * dailyRate * days, 2, MidpointRounding.AwayFromZero);

            if (accrual <= 0)
            {
                AdvanceMonth(ref year, ref month);
                continue;
            }

            // Step 4: create ProjectedOperation
            results.Add(new ProjectedOperation
            {
                Date = accrualDate,
                Amount = accrual,
                Currency = currency,
                AccountId = (long)account.Id,
                CategoryId = null,
                Tags = null,
                Description = $"Начисление процентов {account.InterestRate.Value:F2}% годовых (авто)",
                TemplateOperationId = 0,
                ScenarioId = null,
                IsRecurring = true,
                IsAutoGenerated = true
            });

            AdvanceMonth(ref year, ref month);
        }

        return results;
    }

    private static void AdvanceMonth(ref int year, ref int month)
    {
        if (++month > 12)
        {
            month = 1;
            year++;
        }
    }

    private static List<ProjectedOperation> GenerateDailyAccruals(
        Account account, decimal initialBalance, string currency,
        DateOnly from, DateOnly to)
    {
        var effectiveTo = account.DepositEndDate.HasValue
            ? (account.DepositEndDate.Value < to ? account.DepositEndDate.Value : to)
            : to;

        var dailyRate = account.InterestRate!.Value / 100m / 365m;
        var results = new List<ProjectedOperation>();
        var runningBalance = initialBalance;

        for (var date = from; date <= effectiveTo; date = date.AddDays(1))
        {
            var accrual = Math.Round(runningBalance * dailyRate, 2, MidpointRounding.AwayFromZero);
            if (accrual <= 0) continue;

            results.Add(new ProjectedOperation
            {
                Date = date,
                Amount = accrual,
                Currency = currency,
                AccountId = (long)account.Id,
                CategoryId = null,
                Tags = null,
                Description = $"Ежедневное начисление {account.InterestRate.Value:F2}% годовых",
                TemplateOperationId = 0,
                ScenarioId = null,
                IsRecurring = true,
                IsAutoGenerated = true
            });

            runningBalance += accrual;
        }

        return results;
    }
}
